openapi: 3.0.0
info:
  title: API Laravel
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /api/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /api/login:
    post:
      summary: Authenticate a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
  /api/logout:
    post:
      summary: Logout the current user
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Logged out successfully
  /api/profile:
    get:
      summary: Retrieve the current user's profile
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Profile information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    patch:
      summary: Update the user's profile
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileRequest'
      responses:
        '200':
          description: Profile updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      summary: Delete the user's account
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Account deleted
  /api/sso/redirect/{provider}:
    get:
      summary: Redirect to SSO provider
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirecting to provider
  /api/sso/callback/{provider}:
    get:
      summary: Handle SSO callback
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: SSO login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RegisterRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        password_confirmation:
          type: string
      required:
        - name
        - email
        - password
        - password_confirmation
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password
    UpdateProfileRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
          format: email
        email_verified_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    AuthToken:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: '#/components/schemas/User'
